### PR TITLE
Support zst (Zstandard) file compression format

### PR DESCRIPTION
**Pull request by felixsch**
I thought I might help here a little bit and add basic support for `zstandard` (https://github.com/ikapelyukhin/repomd-parser/issues/12)

I also tried to use a streaming version and failed when reading bigger files, since `nokogiri` will read `4000` characters by default which is not working with the streaming implementation on `zstd-ruby`.

Do you think I missed something?

thanks :)

PS: here is my attempt, maybe you can see the issue if you find motivation and time!

```ruby
class RepomdParser::ZstdIO
  def initialize(handle)
    @fd = handle
    @stream = Zstd::StreamingDecompress.new
  end

  def self.open(filename)
    RepomdParser::ZstdIO.new(File.open(filename, 'rb'))
  end

  def read(len = nil, out = nil)
    data = @fd.read(len, out)
    @stream.decompress(data)
  end

  def close
    @fd.close
  end
end
```

### CODE REVIEW

**Comment by felixsch** [comment]
ping? @ikapelyukhin Can I do anything to help you here?

**Comment by ikapelyukhin** [comment]
> ping? @ikapelyukhin Can I do anything to help you here?

Pong. I'll take a look today.

**Comment by ikapelyukhin** [comment]
The size of decompressed data would be greater than the size of uncompressed data. Probably a bad idea to return more bytes to Nokogiri than it has asked for. I would expect something like this to work, but the output is still coming out truncated:

```ruby
class RepomdParser::ZstdIO
  def initialize(handle)
    @fd = handle
    @stream = Zstd::StreamingDecompress.new
    @buffer = ""
  end

  def self.open(filename)
    RepomdParser::ZstdIO.new(File.open(filename, 'rb'))
  end

  def read(len = nil, out = nil)
    data = @fd.read(len)
    @buffer << @stream.decompress(data) if data

    out = @buffer[0, len-1]
    @buffer = @buffer[len..-1]

    return out
  end

  def close
    @fd.close
  end
end
```

Not sure what's up. Probably a good idea to inherit from `IO` or maybe `StringIO`. Not sure if Nokogiri is calling any other methods (e.g. `closed?`) to detect EOF. Might be worthwhile to examine which methods are called on the filehandle that's passed to Nokogiri.

How large is the largest metadata file we are dealing with?

**Comment by felixsch** [comment]
So I took another shot at implementing the streaming IO for `zstd`. It looks like `libxml` is somehow not considering the last read it performs, which results in the truncated parsing. When debugging, it is clear that `zstd` performs a complete decompression.

But I had a rough time, finding out when and how exactly `libxml` requests more data from the IO object.

Regarding the size of the big XML files. I checked `primary.xml` files and the biggest found was compressed `15mib` vs `130mib` uncompressed.  I think this is still reasonable from my perspective.

What do you think?

**Comment by ikapelyukhin** [comment]
> So I took another shot at implementing the streaming IO for `zstd`. It looks like `libxml` is somehow not considering the last read it performs, which results in the truncated parsing. When debugging, it is clear that `zstd` performs a complete decompression.
> 
> But I had a rough time, finding out when and how exactly `libxml` requests more data from the IO object.

I'll take another look at that IO thing, would be nice to get it working.

**Comment by felixsch** [comment]
Happy new year!

Any updates here @ikapelyukhin?

Since tumbleweed already uses this format it is only a matter of time for all other repositories to follow. Can we have at least the support here, even if its not nice for now?

**Comment by ikapelyukhin** [comment]
> Happy new year!
> 
> Any updates here @ikapelyukhin?
> 
> Since tumbleweed already uses this format it is only a matter of time for all other repositories to follow. Can we have at least the support here, even if its not nice for now?

Yep, I got it working. I'll push the changes to the top of your fork in a bit.

**Comment by ikapelyukhin** [comment]
@felixsch OK, I've opened https://github.com/felixsch/repomd-parser/pull/1.

**Comment by felixsch** [comment]
Thank you and sorry for the long reply time :) Busy times! I merged it and its ready to be applied here :) Thank you so much for helping here! @ikapelyukhin

**Comment by felixsch** [comment]
@ikapelyukhin do mind also making a release :)

**Comment by ikapelyukhin** [comment]
@felixsch please also give #14 a look and I will do a release.

**Pull request merged**
